testMultiply (__main__.TestEchecs) ... FAIL

======================================================================
FAIL: testMultiply (__main__.TestEchecs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thomas/PRO3600-18-BRU-31/Interface Graphique/unitTests.py", line 21, in testMultiply
    self.assertEqual(expected, actual,"failed test for 3x4")
AssertionError: 11 != 12 : failed test for 3x4

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
